export const FETCH_TOPICS = "FETCH_TOPICS";
export const IS_FETCHING_TOPICS = "IS_FETCHING_TOPICS";
export const ADD_TOPIC_ANSWER = "ADD_TOPIC_ANSWER";
export const IS_ADDING_TOPIC_ANSWER = "IS_ADDING_TOPIC_ANSWER";
