export const ADD_MESSAGE_NOTIFICATION = "ADD_MESSAGE_NOTIFICATION";
export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const DELETE_MESSAGE_NOTIFICATIONS = "DELETE_MESSAGE_NOTIFICATIONS";
