export const ADD_MESSAGE_NOTIFICATION = "ADD_MESSAGE_NOTIFICATION";
export const ADD_LIKE_NOTIFICATION = "ADD_LIKE_NOTIFICATION";
export const ADD_MATCH_NOTIFICATION = "ADD_MATCH_NOTIFICATION";
export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const DELETE_MESSAGE_NOTIFICATIONS = "DELETE_MESSAGE_NOTIFICATIONS";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
