export const FETCH_PHOTOS = "FETCH_PHOTOS";
export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const SET_PROFILE_PHOTO = "SET_PROFILE_PHOTO";
export const IS_UPLOADING_PHOTO = "IS_UPLOADING_PHOTO";
export const IS_FETCHING_PHOTOS = "IS_FETCHING_PHOTOS";
export const UPLOAD_PHOTO_FAIL = "UPLOAD_PHOTO_FAIL";
export const CLEAR_UPLOAD_PHOTO_ERRORS = "CLEAR_UPLOAD_PHOTO_ERRORS";
export const REMOVE_PHOTO = "REMOVE_PHOTO";
