export const FETCH_PHOTOS = "FETCH_PHOTOS";
export const UPLOAD_PHOTO = "UPLOAD_PHOTO";
export const PENDING_API_CALL = "PENDING_API_CALL";
export const UPLOAD_PHOTO_FAIL = "UPLOAD_PHOTO_FAIL";
export const CLEAR_UPLOAD_PHOTO_ERRORS = "CLEAR_UPLOAD_PHOTO_ERRORS";
