export const FETCH_USER_PREFERENCES = "FETCH_USER_PREFERENCES";
export const POST_USER_PREFERENCES = "POST_USER_PREFERENCES";
export const LOADING_USER_PREFERENCES = "LOADING_USER_PREFERENCES";
export const POSTING_USER_PREFERENCES = "POSTING_USER_PREFERENCES";
